/** @type {import('next').NextConfig} */
const nextConfig = {
    env: {
        NEXT_APPWRITE_ENDPOINT: process.env.NEXT_APPWRITE_ENDPOINT,
        NEXT_APPWRITE_PROJECT: process.env.NEXT_APPWRITE_PROJECT,
        NEXT_APPWRITE_API_KEY: process.env.NEXT_APPWRITE_API_KEY,
        NEXT_APPWRITE_DATABASE_ID: process.env.NEXT_APPWRITE_DATABASE_ID,
        NEXT_APPWRITE_COLLECTION_PIZZA_ID: process.env.NEXT_APPWRITE_COLLECTION_PIZZA_ID,
        NEXT_APPWRITE_COLLECTION_BURGER_ID: process.env.NEXT_APPWRITE_COLLECTION_BURGER_ID,
        NEXT_APPWRITE_COLLECTION_PITABREAD_ID: process.env.NEXT_APPWRITE_COLLECTION_PITABREAD_ID,
        NEXT_APPWRITE_COLLECTION_DURUM_ID: process.env.NEXT_APPWRITE_COLLECTION_DURUM_ID,
        NEXT_APPWRITE_COLLECTION_WHOLEMENU_ID: process.env.NEXT_APPWRITE_COLLECTION_WHOLEMENU_ID,
        NEXT_APPWRITE_STORAGE_ID: process.env.NEXT_APPWRITE_STORAGE_ID,
        NEXT_APPWRITE_COLLECTION_EMAILS_ID: process.env.NEXT_APPWRITE_COLLECTION_EMAILS_ID,
        NEXT_APPWRITE_COLLECTION_RATING: process.env.NEXT_APPWRITE_COLLECTION_RATING,
        NEXT_APPWRITE_COLLECTION_MENU_ID: process.env.NEXT_APPWRITE_COLLECTION_MENU_ID,
    },
    images: {
        remotePatterns: [
            {
                protocol: "https",
                hostname: "cloud.appwrite.io", 
            },
        ],
    },
};

export default nextConfig;
